### ISSUE TITLE
Incompatible with OpenCV 3.0 or greater

### ISSUE THREAD

**Issue by ehamwey** [a7ul/ImShow-Java-OpenCV#2]
When running the showImage() method in OpenCV 3.0 or greater, an exception is returned:

`Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/opencv/highgui/Highgui`

This is because Highgui has been removed in opencv 3.0 and split into two different packages - see this stackexchange for more details http://stackoverflow.com/questions/25059576/highgui-is-missing-from-opencv-3-0-0-jar

**Comment by AnEmortalKid** [comment]
I might have a local version that works on 3.0 if you check my repo it
might be there.

**Comment by AnEmortalKid** [comment]
@ehamwey here's an imshow that works on 3.0 - https://github.com/AnEmortalKid/Imshow/blob/stable/src/test/java/com/anemortalkid/imshow/Imshow.java
Feel free to rename it to ImShow3 and  you can probably PR it into this guy.

**Comment by pflingstring** [comment]
The source code **does** work on OpenCV >= 3.0. Apparently only the _.jar_ file wasn't updated.
After building the _.jar_ file anew with the current code it works.
Tested on OpenCV 3.2.0

**Comment by jalr4ever** [comment]
The same exception, it do work out only in lower version...

**Comment by AnEmortalKid** [comment]
@setihex would this version work for you: https://github.com/AnEmortalKid/Imshow
